/** Safely organize the Agentic Awesome Skills catalog into Cue profiles. */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmdirSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, posix, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";

export const AAS_REPO = "sickn33/agentic-awesome-skills";
export const AAS_PROFILE_MAX_SKILLS = 24;
export const GENERATED_AAS_PROFILE_MARKER =
  "# Generated by scripts/generate-aas-profiles.ts; edit the organizer, not this file.\n";

export type AasRisk = "safe" | "none" | "critical" | "offensive";

export interface AasSkill {
  id: string;
  name: string;
  description: string;
  category: string;
  path: string;
  risk: AasRisk;
  tags: string[];
}

export interface ParsedAasCatalog {
  skills: AasSkill[];
  invalidEntries: number;
}

export interface AasProfilePlan {
  name: string;
  description: string;
  inherits: string;
  skills: AasSkill[];
  catalog: {
    source: "agentic-awesome-skills";
    group: string;
    capability: string;
    generated: true;
    discoverability: "search";
    reviewRequired?: true;
  };
}

export interface PlanAasProfilesOptions {
  maxSkillsPerProfile?: number;
  reservedProfileNames?: readonly string[];
  reservedSkillIds?: readonly string[];
}

export type AasAssignmentMethod = "override" | "category" | "keyword" | "fallback" | "ambiguous";
export type AasAssignmentConfidence = "high" | "medium" | "low";

export interface AasAssignmentAudit {
  skillId: string;
  profileName: string;
  group: string;
  capability: string;
  method: AasAssignmentMethod;
  confidence: AasAssignmentConfidence;
  score: number;
  runnerUpScore: number;
  margin: number;
  matchedKeywords: string[];
  reviewRequired: boolean;
}

export interface AasPossibleVariantGroup {
  canonicalSkillId: string;
  variantSkillIds: string[];
}

export interface AasCatalogOrganization {
  profiles: AasProfilePlan[];
  assignments: AasAssignmentAudit[];
  possibleVariantGroups: AasPossibleVariantGroup[];
  shadowedSkillIds: string[];
}

export interface CatalogCluster {
  id: string;
  summary: string;
  categories?: string[];
  keywords?: string[];
  fallback?: boolean;
}

export interface CatalogDomain {
  id: string;
  inherits: string;
  summary: string;
  categories: string[];
  keywords: string[];
  clusters?: CatalogCluster[];
}

interface DomainDecision {
  domain: CatalogDomain;
  capability?: string;
  method: AasAssignmentMethod;
  confidence: AasAssignmentConfidence;
  score: number;
  runnerUpScore: number;
  margin: number;
  matchedKeywords: string[];
  reviewRequired: boolean;
}

interface CatalogAssignmentOverride {
  domain: string;
  capability?: string;
}

const REVIEW_DOMAIN: CatalogDomain = {
  id: "review-needed",
  inherits: "core",
  summary: "Ambiguous catalog entries awaiting a human taxonomy decision.",
  categories: [],
  keywords: [],
};

const AAS_TAXONOMY_PATH = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../../resources/catalogs/aas-taxonomy.yaml",
);

function taxonomyStringList(value: unknown, field: string): string[] {
  if (!Array.isArray(value) || value.some((entry) => typeof entry !== "string" || entry.trim() === "")) {
    throw new Error(`AAS taxonomy field ${field} must be an array of non-empty strings.`);
  }
  return value.map((entry) => entry.trim());
}

function parseCatalogCluster(raw: unknown, domainId: string, index: number): CatalogCluster {
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    throw new Error(`AAS taxonomy domain ${domainId} cluster ${index} must be an object.`);
  }
  const item = raw as Record<string, unknown>;
  const id = cleanText(item.id);
  const summary = cleanText(item.summary);
  if (!/^[a-z0-9][a-z0-9-]*$/.test(id) || !summary) {
    throw new Error(`AAS taxonomy domain ${domainId} has an invalid cluster at index ${index}.`);
  }
  return {
    id,
    summary,
    ...(item.categories === undefined
      ? {}
      : { categories: taxonomyStringList(item.categories, `${domainId}.${id}.categories`) }),
    ...(item.keywords === undefined
      ? {}
      : { keywords: taxonomyStringList(item.keywords, `${domainId}.${id}.keywords`) }),
    ...(item.fallback === undefined
      ? {}
      : typeof item.fallback === "boolean"
        ? { fallback: item.fallback }
        : (() => { throw new Error(`AAS taxonomy field ${domainId}.${id}.fallback must be boolean.`); })()),
  };
}

export function parseAasTaxonomy(raw: unknown): readonly CatalogDomain[] {
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    throw new Error("AAS taxonomy must be an object.");
  }
  const root = raw as Record<string, unknown>;
  if (root.version !== 1 || !Array.isArray(root.domains) || root.domains.length === 0) {
    throw new Error("AAS taxonomy must declare version: 1 and a non-empty domains array.");
  }

  const domains: CatalogDomain[] = [];
  const domainIds = new Set<string>();
  const categories = new Set<string>();
  for (const [index, rawDomain] of root.domains.entries()) {
    if (rawDomain === null || typeof rawDomain !== "object" || Array.isArray(rawDomain)) {
      throw new Error(`AAS taxonomy domain ${index} must be an object.`);
    }
    const item = rawDomain as Record<string, unknown>;
    const id = cleanText(item.id);
    const inherits = cleanText(item.inherits);
    const summary = cleanText(item.summary);
    if (!/^[a-z0-9][a-z0-9-]*$/.test(id) || !/^[a-z][a-z0-9-]*$/.test(inherits) || !summary) {
      throw new Error(`AAS taxonomy domain ${index} has invalid id, inherits, or summary fields.`);
    }
    if (domainIds.has(id)) throw new Error(`AAS taxonomy has duplicate domain id: ${id}.`);
    domainIds.add(id);
    const domainCategories = taxonomyStringList(item.categories, `${id}.categories`).map(slug);
    for (const category of domainCategories) {
      if (categories.has(category)) {
        throw new Error(`AAS taxonomy category ${category} belongs to more than one domain.`);
      }
      categories.add(category);
    }
    const clusters = item.clusters === undefined
      ? undefined
      : Array.isArray(item.clusters)
        ? item.clusters.map((cluster, clusterIndex) => parseCatalogCluster(cluster, id, clusterIndex))
        : (() => { throw new Error(`AAS taxonomy field ${id}.clusters must be an array.`); })();
    if (clusters && new Set(clusters.map((cluster) => cluster.id)).size !== clusters.length) {
      throw new Error(`AAS taxonomy domain ${id} has duplicate cluster ids.`);
    }
    domains.push({
      id,
      inherits,
      summary,
      categories: domainCategories,
      keywords: taxonomyStringList(item.keywords, `${id}.keywords`),
      ...(clusters ? { clusters } : {}),
    });
  }
  if (!domainIds.has("general")) throw new Error("AAS taxonomy must include a general domain.");
  parseTaxonomyOverrides(root, domains);
  parseTaxonomyShadowed(root);
  return domains;
}

function parseTaxonomyOverrides(
  root: Record<string, unknown>,
  domains: readonly CatalogDomain[],
): Map<string, CatalogAssignmentOverride> {
  const raw = root.overrides;
  if (raw === undefined) return new Map();
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    throw new Error("AAS taxonomy overrides must be an object keyed by skill id.");
  }
  const byDomain = new Map(domains.map((domain) => [domain.id, domain]));
  const overrides = new Map<string, CatalogAssignmentOverride>();
  for (const [skillId, value] of Object.entries(raw as Record<string, unknown>)) {
    if (!/^[a-z0-9][a-z0-9_-]*$/.test(skillId)) {
      throw new Error(`AAS taxonomy override has invalid skill id: ${skillId}.`);
    }
    if (value === null || typeof value !== "object" || Array.isArray(value)) {
      throw new Error(`AAS taxonomy override ${skillId} must be an object.`);
    }
    const item = value as Record<string, unknown>;
    const domainId = cleanText(item.domain);
    const domain = byDomain.get(domainId);
    if (!domain) {
      throw new Error(`AAS taxonomy override ${skillId} references unknown domain: ${domainId}.`);
    }
    const capability = item.capability === undefined ? undefined : cleanText(item.capability);
    if (capability !== undefined) {
      if (!capability || !domain.clusters?.some((cluster) => cluster.id === capability)) {
        throw new Error(
          `AAS taxonomy override ${skillId} references unknown capability ${domainId}/${capability}.`,
        );
      }
    }
    overrides.set(skillId, { domain: domainId, ...(capability ? { capability } : {}) });
  }
  return overrides;
}

function parseTaxonomyShadowed(root: Record<string, unknown>): Map<string, string> {
  const raw = root.shadowed;
  if (raw === undefined) return new Map();
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    throw new Error("AAS taxonomy shadowed entries must be an object keyed by catalog skill id.");
  }
  const shadowed = new Map<string, string>();
  for (const [skillId, localSkillId] of Object.entries(raw as Record<string, unknown>)) {
    if (!/^[a-z0-9][a-z0-9_-]*$/.test(skillId)) {
      throw new Error(`AAS taxonomy shadowed entry has invalid catalog skill id: ${skillId}.`);
    }
    if (typeof localSkillId !== "string" || !/^[a-z0-9][a-z0-9-]*(?:\/[a-z0-9][a-z0-9-]*)+$/.test(localSkillId)) {
      throw new Error(`AAS taxonomy shadowed entry ${skillId} has invalid local skill id.`);
    }
    shadowed.set(skillId, localSkillId);
  }
  return shadowed;
}

function loadAasTaxonomy(
  path: string = AAS_TAXONOMY_PATH,
): {
  domains: readonly CatalogDomain[];
  overrides: Map<string, CatalogAssignmentOverride>;
  shadowed: Map<string, string>;
} {
  try {
    const raw = parseYaml(readFileSync(path, "utf8"));
    const domains = parseAasTaxonomy(raw);
    return {
      domains,
      overrides: parseTaxonomyOverrides(raw as Record<string, unknown>, domains),
      shadowed: parseTaxonomyShadowed(raw as Record<string, unknown>),
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Cannot load AAS taxonomy at ${path}: ${message}`);
  }
}

const LOADED_TAXONOMY = loadAasTaxonomy();
const DOMAINS = LOADED_TAXONOMY.domains;
const TAXONOMY_OVERRIDES = LOADED_TAXONOMY.overrides;
const TAXONOMY_SHADOWED = LOADED_TAXONOMY.shadowed;
export const AAS_TAXONOMY: readonly CatalogDomain[] = DOMAINS;

const DOMAIN_BY_CATEGORY = new Map(
  DOMAINS.flatMap((domain) =>
    domain.categories.map((category) => [slug(category), domain] as const)),
);

export function parseAasCatalog(raw: unknown): ParsedAasCatalog {
  if (!Array.isArray(raw)) return { skills: [], invalidEntries: 1 };
  const byId = new Map<string, AasSkill>();
  let invalidEntries = 0;
  for (const item of raw) {
    const parsed = parseAasSkill(item);
    if (!parsed) {
      invalidEntries++;
      continue;
    }
    if (byId.has(parsed.id)) {
      invalidEntries++;
      continue;
    }
    byId.set(parsed.id, parsed);
  }
  return {
    skills: [...byId.values()].sort((a, b) => a.id.localeCompare(b.id)),
    invalidEntries,
  };
}

function parseAasSkill(raw: unknown): AasSkill | null {
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) return null;
  const item = raw as Record<string, unknown>;
  const id = cleanText(item.id);
  const path = safeSkillPath(item.path);
  const risk = item.risk;
  if (
    !/^[a-z0-9][a-z0-9_-]*$/.test(id)
    || !path
    || (risk !== "safe" && risk !== "none" && risk !== "critical" && risk !== "offensive")
  ) {
    return null;
  }
  return {
    id,
    name: cleanText(item.name) || id,
    description: cleanText(item.description),
    category: cleanText(item.category) || "uncategorized",
    path,
    risk,
    tags: Array.isArray(item.tags)
      ? item.tags.map(cleanText).filter(Boolean)
      : [],
  };
}

function cleanText(value: unknown): string {
  return typeof value === "string" ? value.trim().replace(/\s+/g, " ") : "";
}

function safeSkillPath(value: unknown): string | null {
  const path = cleanText(value);
  if (!path || path.includes("\\") || path.startsWith("/")) return null;
  const normalized = posix.normalize(path);
  if (normalized === ".." || normalized.startsWith("../")) return null;
  return normalized.startsWith("skills/") ? normalized : null;
}

export function planAasProfiles(
  catalog: readonly AasSkill[],
  options: PlanAasProfilesOptions = {},
): AasProfilePlan[] {
  return planAasCatalog(catalog, options).profiles;
}

export function planAasCatalog(
  catalog: readonly AasSkill[],
  options: PlanAasProfilesOptions = {},
): AasCatalogOrganization {
  const maxSkills = Math.max(
    1,
    Math.min(100, Math.floor(options.maxSkillsPerProfile ?? AAS_PROFILE_MAX_SKILLS)),
  );
  const reservedNames = new Set(options.reservedProfileNames ?? []);
  const reservedSkillIds = new Set(options.reservedSkillIds ?? []);
  const eligible = catalog
    .filter((skill) =>
      (skill.risk === "safe" || skill.risk === "none")
      && !reservedSkillIds.has(skill.id)
      && !TAXONOMY_SHADOWED.has(skill.id))
    .sort((a, b) => a.id.localeCompare(b.id));
  const grouped = new Map<string, { domain: CatalogDomain; skills: AasSkill[] }>();
  const decisions = new Map<string, DomainDecision>();

  for (const skill of eligible) {
    const decision = classifyDomain(skill);
    const domain = decision.domain;
    decisions.set(skill.id, decision);
    const group = grouped.get(domain.id) ?? { domain, skills: [] };
    group.skills.push(skill);
    grouped.set(domain.id, group);
  }

  const plans: AasProfilePlan[] = [];
  const assignments: AasAssignmentAudit[] = [];
  for (const { domain, skills } of [...grouped.values()].sort((a, b) =>
    a.domain.id.localeCompare(b.domain.id))) {
    const hasForcedCapability = skills.some((skill) => decisions.get(skill.id)?.capability);
    const buckets = domain.clusters && (skills.length > maxSkills || hasForcedCapability)
      ? clusterSkills(domain, skills, decisions)
      : [{ id: "", summary: domain.summary, skills }];
    for (const bucket of buckets.sort((a, b) => a.id.localeCompare(b.id))) {
      const chunks = balancedChunks(bucket.skills, maxSkills);
      for (const [index, chunkSkills] of chunks.entries()) {
        const base = `aas-${domain.id}${bucket.id ? `-${bucket.id}` : ""}`;
        let name = `${base}${index === 0 ? "" : `-${index + 1}`}`;
        let conflictSuffix = index + 2;
        while (reservedNames.has(name)) {
          name = `${base}-${conflictSuffix++}`;
        }
        reservedNames.add(name);
        const group = domain.id === REVIEW_DOMAIN.id ? "review" : domain.id;
        const capability = bucket.id || "general";
        const reviewRequired = domain.id === REVIEW_DOMAIN.id;
        plans.push({
          name,
          description: profileDescription(bucket.summary, domain.inherits),
          inherits: domain.inherits,
          skills: chunkSkills,
          catalog: {
            source: "agentic-awesome-skills",
            group,
            capability,
            generated: true,
            discoverability: "search",
            ...(reviewRequired ? { reviewRequired: true as const } : {}),
          },
        });
        for (const skill of chunkSkills) {
          const decision = decisions.get(skill.id)!;
          assignments.push({
            skillId: skill.id,
            profileName: name,
            group,
            capability,
            method: decision.method,
            confidence: decision.confidence,
            score: decision.score,
            runnerUpScore: decision.runnerUpScore,
            margin: decision.margin,
            matchedKeywords: decision.matchedKeywords,
            reviewRequired: decision.reviewRequired,
          });
        }
      }
    }
  }
  return {
    profiles: plans.sort((a, b) => a.name.localeCompare(b.name)),
    assignments: assignments.sort((a, b) => a.skillId.localeCompare(b.skillId)),
    possibleVariantGroups: findPossibleVariantGroups(eligible),
    shadowedSkillIds: catalog
      .filter((skill) =>
        (skill.risk === "safe" || skill.risk === "none")
        && TAXONOMY_SHADOWED.has(skill.id))
      .map((skill) => skill.id)
      .sort((a, b) => a.localeCompare(b)),
  };
}

function classifyDomain(skill: AasSkill): DomainDecision {
  const override = TAXONOMY_OVERRIDES.get(skill.id);
  if (override) {
    const domain = DOMAINS.find((candidate) => candidate.id === override.domain)!;
    return {
      domain,
      capability: override.capability,
      method: "override",
      confidence: "high",
      score: 100,
      runnerUpScore: 0,
      margin: 100,
      matchedKeywords: [`override:${override.domain}${override.capability ? `/${override.capability}` : ""}`],
      reviewRequired: false,
    };
  }
  const direct = DOMAIN_BY_CATEGORY.get(slug(skill.category));
  if (direct) {
    return {
      domain: direct,
      method: "category",
      confidence: "high",
      score: 100,
      runnerUpScore: 0,
      margin: 100,
      matchedKeywords: [`category:${slug(skill.category)}`],
      reviewRequired: false,
    };
  }
  const terms = skillTerms(skill);
  const ranked = DOMAINS
    .filter((domain) => domain.id !== "general")
    .map((domain, index) => ({
      domain,
      index,
      score: phraseScore(domain.keywords, terms),
      matchedKeywords: matchedPhrases(domain.keywords, terms),
    }))
    .sort((a, b) => b.score - a.score || a.index - b.index);
  const top = ranked[0];
  const runnerUpScore = ranked[1]?.score ?? 0;
  if (!top || top.score === 0) {
    return {
      domain: REVIEW_DOMAIN,
      method: "fallback",
      confidence: "low",
      score: 0,
      runnerUpScore,
      margin: 0,
      matchedKeywords: [],
      reviewRequired: true,
    };
  }
  const margin = top.score - runnerUpScore;
  if (margin === 0) {
    return {
      domain: REVIEW_DOMAIN,
      method: "ambiguous",
      confidence: "low",
      score: top.score,
      runnerUpScore,
      margin,
      matchedKeywords: top.matchedKeywords,
      reviewRequired: true,
    };
  }
  return {
    domain: top.domain,
    method: "keyword",
    confidence: margin >= 8 && top.score >= 8 ? "high" : "medium",
    score: top.score,
    runnerUpScore,
    margin,
    matchedKeywords: top.matchedKeywords,
    reviewRequired: false,
  };
}

function clusterSkills(
  domain: CatalogDomain,
  skills: readonly AasSkill[],
  decisions: ReadonlyMap<string, DomainDecision>,
): Array<{ id: string; summary: string; skills: AasSkill[] }> {
  const clusters = domain.clusters ?? [];
  const fallback = clusters.find((cluster) => cluster.fallback) ?? clusters.at(-1);
  const grouped = new Map<string, { definition: CatalogCluster; skills: AasSkill[] }>();
  for (const cluster of clusters) {
    grouped.set(cluster.id, { definition: cluster, skills: [] });
  }

  for (const skill of skills) {
    const forcedCapability = decisions.get(skill.id)?.capability;
    if (forcedCapability) {
      grouped.get(forcedCapability)!.skills.push(skill);
      continue;
    }
    const terms = skillTerms(skill);
    const category = slug(skill.category);
    const ranked = clusters
      .map((cluster, index) => ({
        cluster,
        index,
        score: (cluster.categories?.map(slug).includes(category) ? 6 : 0)
          + phraseScore(cluster.keywords ?? [], terms),
      }))
      .filter((entry) => !entry.cluster.fallback)
      .sort((a, b) => b.score - a.score || a.index - b.index);
    const selected = ranked[0] && ranked[0].score > 0 ? ranked[0].cluster : fallback;
    if (selected) grouped.get(selected.id)!.skills.push(skill);
  }

  return [...grouped.values()]
    .filter((entry) => entry.skills.length > 0)
    .map((entry) => ({
      id: entry.definition.id,
      summary: entry.definition.summary,
      skills: entry.skills.sort((a, b) => a.id.localeCompare(b.id)),
    }));
}

function skillTerms(skill: AasSkill): Set<string> {
  return new Set(tokenize([
    skill.id,
    skill.name,
    skill.category,
    ...skill.tags,
    skill.description,
  ].join(" ")));
}

function phraseScore(keywords: readonly string[], terms: ReadonlySet<string>): number {
  let score = 0;
  for (const keyword of keywords) {
    const pieces = tokenize(keyword);
    if (pieces.length > 0 && pieces.every((piece) => matchesTerm(terms, piece))) {
      score += pieces.length * 4;
    }
  }
  return score;
}

function matchedPhrases(keywords: readonly string[], terms: ReadonlySet<string>): string[] {
  return keywords.filter((keyword) => {
    const pieces = tokenize(keyword);
    return pieces.length > 0 && pieces.every((piece) => matchesTerm(terms, piece));
  });
}

function matchesTerm(terms: ReadonlySet<string>, expected: string): boolean {
  if (terms.has(expected)) return true;
  if (expected.length < 4) return false;
  return [...terms].some((term) => term.startsWith(expected));
}

function tokenize(value: string): string[] {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .filter((term) => term.length > 1);
}

function slug(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);
}

function balancedChunks<T>(items: readonly T[], maxSize: number): T[][] {
  if (items.length === 0) return [];
  const chunkCount = Math.ceil(items.length / maxSize);
  if (chunkCount === 1) return [items.slice()];

  const baseSize = Math.floor(items.length / chunkCount);
  const largerChunks = items.length % chunkCount;
  const chunks: T[][] = [];
  let offset = 0;
  for (let index = 0; index < chunkCount; index++) {
    const size = baseSize + (index < largerChunks ? 1 : 0);
    chunks.push(items.slice(offset, offset + size));
    offset += size;
  }
  return chunks;
}

function findPossibleVariantGroups(skills: readonly AasSkill[]): AasPossibleVariantGroup[] {
  const byDescription = new Map<string, string[]>();
  for (const skill of skills) {
    const normalized = skill.description
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, " ")
      .trim();
    if (normalized.length < 40) continue;
    const ids = byDescription.get(normalized) ?? [];
    ids.push(skill.id);
    byDescription.set(normalized, ids);
  }
  return [...byDescription.values()]
    .filter((ids) => ids.length > 1)
    .map((ids) => {
      const sorted = [...ids].sort((a, b) => a.localeCompare(b));
      return {
        canonicalSkillId: sorted[0]!,
        variantSkillIds: sorted.slice(1),
      };
    })
    .sort((a, b) => a.canonicalSkillId.localeCompare(b.canonicalSkillId));
}

function profileDescription(summary: string, inherits: string): string {
  const suffix = inherits === "core"
    ? "Opt-in AAS extension for Cue."
    : `Opt-in AAS extension for Cue's ${inherits} profile.`;
  return `${summary} ${suffix}`.slice(0, 200);
}

export interface AasProfileAssignments {
  profileNames: string[];
  skillIds: string[];
  duplicateSkillIds: string[];
}

export function readAasProfileAssignments(
  profilesDir: string,
  options: { includeGenerated?: boolean } = {},
): AasProfileAssignments {
  const profileNames: string[] = [];
  const skillIds: string[] = [];
  let entries: string[] = [];
  try {
    entries = readdirSync(profilesDir);
  } catch {
    return { profileNames, skillIds, duplicateSkillIds: [] };
  }
  for (const name of entries.sort((a, b) => a.localeCompare(b))) {
    if (!/^aas-[a-z0-9][a-z0-9-]{0,58}$/.test(name)) continue;
    const path = join(profilesDir, name, "profile.yaml");
    if (!existsSync(path)) continue;
    const text = readFileSync(path, "utf8");
    if (!options.includeGenerated && text.startsWith(GENERATED_AAS_PROFILE_MARKER)) continue;
    let parsed: unknown;
    try {
      parsed = parseYaml(text);
    } catch {
      continue;
    }
    if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) continue;
    profileNames.push(name);
    const refs = (parsed as { skills?: { npx?: unknown } }).skills?.npx;
    if (!Array.isArray(refs)) continue;
    for (const ref of refs) {
      if (ref === null || typeof ref !== "object" || Array.isArray(ref)) continue;
      const item = ref as { repo?: unknown; skills?: unknown };
      if (item.repo !== AAS_REPO || !Array.isArray(item.skills)) continue;
      for (const id of item.skills) {
        if (typeof id === "string" && /^[a-z0-9][a-z0-9_-]*$/.test(id)) skillIds.push(id);
      }
    }
  }
  const counts = new Map<string, number>();
  for (const id of skillIds) counts.set(id, (counts.get(id) ?? 0) + 1);
  return {
    profileNames,
    skillIds: [...new Set(skillIds)].sort((a, b) => a.localeCompare(b)),
    duplicateSkillIds: [...counts.entries()]
      .filter(([, count]) => count > 1)
      .map(([id]) => id)
      .sort((a, b) => a.localeCompare(b)),
  };
}

export interface WriteAasProfilesOptions {
  profilesDir: string;
  sourceRevision: string;
  pruneStaleGenerated?: boolean;
}

export interface WriteAasProfilesResult {
  created: string[];
  updated: string[];
  removed: string[];
  skipped: string[];
}

export function writeAasProfiles(
  plans: readonly AasProfilePlan[],
  options: WriteAasProfilesOptions,
): WriteAasProfilesResult {
  if (!/^[a-f0-9]{40}$/i.test(options.sourceRevision)) {
    throw new Error("AAS source revision must be a full 40-character Git SHA.");
  }
  mkdirSync(options.profilesDir, { recursive: true });
  const result: WriteAasProfilesResult = {
    created: [],
    updated: [],
    removed: [],
    skipped: [],
  };
  const plannedNames = new Set(plans.map((plan) => plan.name));

  for (const plan of plans) {
    if (!/^aas-[a-z0-9][a-z0-9-]{0,58}$/.test(plan.name)) continue;
    const directory = join(options.profilesDir, plan.name);
    const path = join(directory, "profile.yaml");
    const next = renderAasProfile(plan, options.sourceRevision);
    if (existsSync(path)) {
      const current = readFileSync(path, "utf8");
      if (!current.startsWith(GENERATED_AAS_PROFILE_MARKER)) {
        result.skipped.push(plan.name);
        continue;
      }
      if (current !== next) {
        writeFileSync(path, next);
        result.updated.push(plan.name);
      }
      continue;
    }
    mkdirSync(directory, { recursive: true });
    writeFileSync(path, next);
    result.created.push(plan.name);
  }

  if (options.pruneStaleGenerated) {
    for (const name of readdirSync(options.profilesDir).sort((a, b) => a.localeCompare(b))) {
      if (!name.startsWith("aas-") || plannedNames.has(name)) continue;
      const directory = join(options.profilesDir, name);
      const path = join(directory, "profile.yaml");
      if (!existsSync(path)) continue;
      const current = readFileSync(path, "utf8");
      if (!current.startsWith(GENERATED_AAS_PROFILE_MARKER)) continue;
      unlinkSync(path);
      try {
        rmdirSync(directory);
      } catch {
        // Preserve any hand-added companion files in a generated profile directory.
      }
      result.removed.push(name);
    }
  }

  return result;
}

function renderAasProfile(plan: AasProfilePlan, sourceRevision: string): string {
  const yaml = stringifyYaml({
    name: plan.name,
    icon: "📚",
    description: plan.description,
    kind: "overlay",
    catalog: plan.catalog,
    inherits: plan.inherits,
    skills: {
      local: [],
      npx: [{
        repo: AAS_REPO,
        pin: `git@${sourceRevision}`,
        skills: plan.skills.map((skill) => skill.id),
      }],
    },
    mcps: [],
  });
  return GENERATED_AAS_PROFILE_MARKER + yaml;
}
