/**
 * Catalog index — the shared contract behind on-demand skill resolution.
 *
 * `catalog.json` is generated by a bash+jq script and carries name, description,
 * source, category, tags, triggers and links. That's most of what a matcher
 * needs, but two of those fields are thin (triggers 122/452, tags 87/452) and
 * three useful ones are missing entirely: `capability`, `notFor`, and the MCP
 * servers a skill depends on.
 *
 * Rather than teach the bash generator to infer capability from prose — which
 * would mean reimplementing `skill-router.ts` in awk — this module derives a
 * richer `index.json` from `catalog.json` in TypeScript, reusing the parsers
 * that already exist:
 *
 *   parseSkillFromContent  (skill-router)      → triggers, capability, notFor
 *   depsFromContent        (skill-dependencies) → requires.mcps
 *
 * The index is the interface between all three resolution tiers. The Tier 1
 * hook reads the flat `.idx` files emitted by {@link writeMatcherIndex}, Tier 2
 * (`cue resolve`) reads `index.json` directly, and the Tier 3 LLM prompt is
 * built from the same entries. Keeping one artifact — and one set of weights —
 * is what lets the query engine be replaced later without touching the tiers.
 *
 * Scoring weights live HERE and nowhere else. The `.idx` files carry a
 * precomputed weight column so the bash matcher only ever sums numbers; it
 * never encodes a weight of its own. Change a constant below and both tiers
 * move together on the next rebuild.
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, renameSync, statSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, relative, resolve, sep } from "node:path";

import { parse as parseYaml } from "yaml";

import { cacheDir } from "./config-paths";
import { depsFromContent } from "./skill-dependencies";
import { type ParseQuality, parseSkillFromContent } from "./skill-router";

export const INDEX_SCHEMA_VERSION = "2.2";

/** Field weights. The `.idx` files bake these in; bash never re-derives them. */
export const WEIGHTS = {
  /** A full trigger phrase found in the prompt — the strongest signal we have. */
  triggerPhrase: 10,
  name: 4,
  category: 4,
  tag: 3,
  capability: 2,
  description: 1,
  /** Anti-scope hit. Negative: "NOT for X" should push a skill down, not up. */
  notFor: -4,
} as const;

/** Multiplier when ≥2 distinct prompt tokens hit the same skill. Mirrors the
 *  cross-token bonus in `smart-lookup.sh` so the tiers rank alike. */
export const MULTI_TOKEN_BONUS = 1.5;

/** Score a skill must clear before it is worth interrupting the user about. */
export const SUGGEST_THRESHOLD = 6;

/** Shortest token we index or match. Below this, matches are noise. */
export const MIN_TERM_LENGTH = 4;

/**
 * Terms too common to discriminate between 450 skills. English plus Hungarian,
 * because prompts in this workspace are routinely Hungarian and an unfiltered
 * "amikor"/"lehet" would match a third of the catalog.
 */
const STOPWORDS = new Set([
  // English
  "when", "user", "says", "use", "using", "used", "uses", "this", "that", "with",
  "from", "into", "your", "you", "the", "and", "for", "are", "was", "were", "will",
  "should", "would", "could", "want", "wants", "need", "needs", "make", "makes",
  "help", "helps", "also", "them", "they", "their", "there", "here", "what",
  "which", "while", "about", "after", "before", "over", "under", "than", "then",
  "some", "any", "all", "each", "every", "more", "most", "other", "such", "only",
  "just", "like", "well", "even", "back", "down", "out", "off", "own", "same",
  "skill", "skills", "file", "files", "code", "work", "works", "working",
  // Hungarian
  "hogy", "nem", "igen", "csak", "amikor", "akkor", "lehet", "kell", "kellene",
  "legyen", "lenne", "való", "valami", "valami", "ezt", "azt", "ezek", "azok",
  "mint", "vagy", "meg", "már", "még", "most", "majd", "nagyon", "jobban",
  "tudja", "tudod", "tudom", "szeretnem", "szeretném", "olyan", "ilyen",
  "egyik", "másik", "minden", "semmi", "pedig", "hanem", "mert", "miért",
]);

/** One skill, as every tier sees it. */
export interface IndexEntry {
  /** `category/dirname` — derived from the SKILL.md path, not frontmatter, so
   *  it always matches what `cue loadout keep` and `smart-lookup.sh` expect. */
  id: string;
  name: string;
  category: string;
  description: string;
  /** Absolute path to SKILL.md. */
  source: string;
  tags: string[];
  triggers: string[];
  capability: string;
  notFor: string;
  links: string[];
  requires: { mcps: string[] };
  quality: ParseQuality;
}

export interface SkillIndex {
  schema_version: string;
  /**
   * mtime (epoch ms) of the catalog this was derived from.
   *
   * There is deliberately no `generated_at`: the index is a checked-in derived
   * artifact, and a wall-clock stamp made every rebuild produce a one-line diff
   * on a 432K file that nothing read. Staleness is decided by comparing file
   * mtimes, so the content can — and should — be byte-identical for identical
   * input.
   */
  catalog_mtime: number;
  counts: {
    skills: number;
    withTriggers: number;
    withCapability: number;
    withRequires: number;
  };
  skills: IndexEntry[];
  /**
   * `mcp id → profiles that declare it`, precomputed at build time.
   *
   * Needed to answer "this skill wants an MCP you don't have — where do you get
   * it?" honestly. Resolving that at query time would mean loading all ~93
   * profiles through the inheritance chain on every lookup; the answer only
   * changes when a profile changes, so it belongs in the index.
   */
  mcpProviders: Record<string, string[]>;
}

interface CatalogEntry {
  name?: string;
  description?: string;
  source?: string;
  category?: string;
  tags?: string[];
  triggers?: string[];
  links?: string[];
}

/** Repo root, resolved the same way `skill-dependencies` does it. */
function repoRoot(): string {
  return process.env.CUE_REPO_ROOT ?? process.env.SOUL_REPO_ROOT ?? join(homedir(), "Documents", "cue");
}

export function catalogPath(): string {
  return process.env.CUE_CATALOG ?? join(repoRoot(), "resources", "skills", "catalog", "catalog.json");
}

/** `index.json` sits next to `catalog.json` and ships with the repo, so a fresh
 *  clone gets Tier 1 recall without running a build step first. */
export function indexPath(): string {
  return process.env.CUE_SKILL_INDEX ?? join(dirname(catalogPath()), "index.json");
}

export function skillsRoot(): string {
  return process.env.CUE_SKILLS_ROOT ?? join(repoRoot(), "resources", "skills", "skills");
}

/** Derived matcher files for the bash tier. Cache, not repo — cheap to rebuild
 *  from `index.json` and pointless to version. */
export function matcherDir(): string {
  return join(cacheDir(), "skill-index");
}

/**
 * Derive the canonical skill id from its SKILL.md path.
 *
 * The catalog's `name` comes from frontmatter, which drifts from the directory
 * name often enough to matter (`meta/smart-loader`'s frontmatter name is
 * `smart-loader`, but plenty of skills disagree). Every consumer — loadout,
 * smart-lookup, profile.yaml — addresses skills by PATH, so the path wins.
 */
export function idFromSource(source: string, root: string): string | null {
  const rel = relative(resolve(root), resolve(source));
  if (!rel || rel.startsWith("..")) return null;
  const parts = rel.split(sep);
  // <category>/<dirname>/SKILL.md
  if (parts.length < 3 || parts[parts.length - 1] !== "SKILL.md") return null;
  return parts.slice(0, parts.length - 1).join("/");
}

/**
 * Fold a trailing plural "s" so a prompt's "webhook" matches a description's
 * "webhooks". Deliberately crude — a real stemmer is overkill for matching
 * single words against skill descriptions, and anything more aggressive starts
 * conflating distinct terms.
 *
 * ASCII only, on purpose. A trailing "s" means plural in English; in Hungarian
 * it usually doesn't (the plural marker is "-k"), so folding would turn
 * "közbeszerzés" into "közbeszerzé" and destroy the match. Non-ASCII terms are
 * left alone — and since they're indexed and queried through this same
 * function, leaving them alone is consistent on both sides.
 *
 * Other guards: "ss" (class), "us" (status), "is" (analysis), "js" (nextjs,
 * medusajs — a technology suffix, never a plural marker), and anything that
 * would fall under the minimum term length.
 */
function foldPlural(t: string): string {
  if (t.length <= MIN_TERM_LENGTH) return t;
  if (!/^[a-z0-9-]+$/.test(t)) return t;
  if (!t.endsWith("s")) return t;
  if (/(ss|us|is|js)$/.test(t)) return t;
  return t.slice(0, -1);
}

/**
 * Split text into indexable terms: lowercased, punctuation-stripped,
 * plural-folded, stopword filtered, length-bounded.
 *
 * Used for BOTH index build and query parsing. That symmetry is the point — a
 * prompt token and an index term must normalize identically or the match
 * silently fails, which is exactly the class of bug this whole feature exists
 * to fix.
 */
export function tokenize(text: string): string[] {
  const out = new Set<string>();
  for (const raw of text.toLowerCase().split(/[^\p{L}\p{N}_-]+/u)) {
    const trimmed = raw.replace(/^[-_]+|[-_]+$/g, "");
    if (trimmed.length < MIN_TERM_LENGTH || trimmed.length > 30) continue;
    if (STOPWORDS.has(trimmed)) continue;
    const t = foldPlural(trimmed);
    if (t.length < MIN_TERM_LENGTH || STOPWORDS.has(t)) continue;
    out.add(t);
  }
  return [...out];
}

/**
 * Build the enriched index from `catalog.json`.
 *
 * Entries whose SKILL.md can't be read are kept with whatever the catalog knew
 * — a missing file should cost that skill its enrichment, not its existence.
 */
export function buildIndex(opts: { catalog?: string; root?: string } = {}): SkillIndex {
  const catalogFile = opts.catalog ?? catalogPath();
  const root = opts.root ?? skillsRoot();
  const raw = JSON.parse(readFileSync(catalogFile, "utf8")) as { installed?: CatalogEntry[] };
  const installed = Array.isArray(raw.installed) ? raw.installed : [];

  const skills: IndexEntry[] = [];
  for (const entry of installed) {
    const source = entry.source ?? "";
    if (!source) continue;
    const id = idFromSource(source, root) ?? `${entry.category ?? "unknown"}/${entry.name ?? "unknown"}`;

    let content = "";
    try {
      content = readFileSync(source, "utf8");
    } catch {
      /* unreadable — fall through with catalog-only data */
    }

    const parsed = content ? parseSkillFromContent(id, content, entry.name) : null;
    const mcps = content ? [...new Set(depsFromContent(id, content).map((d) => d.mcpId.toLowerCase()))] : [];

    // Union the catalog's triggers with the ones mined from description prose.
    // The catalog only sees explicit `triggers:` frontmatter (122/452); the
    // router also pulls quoted phrases out of the description (~450/452).
    const triggers = dedupeCI([...(entry.triggers ?? []), ...(parsed?.triggers ?? [])]);

    skills.push({
      id,
      name: entry.name ?? id.split("/").pop() ?? id,
      category: entry.category ?? id.split("/")[0] ?? "",
      description: stripWrappingQuotes(entry.description ?? parsed?.rawDescription ?? ""),
      source,
      tags: dedupeCI(entry.tags ?? []),
      triggers,
      capability: parsed?.capability ?? "",
      notFor: parsed?.notFor ?? "",
      links: dedupeCI(entry.links ?? []),
      requires: { mcps },
      quality: parsed?.quality ?? "none",
    });
  }

  let catalogMtime = 0;
  try {
    catalogMtime = statSync(catalogFile).mtimeMs;
  } catch {
    /* keep 0 — forces a rebuild next time rather than trusting a bad stat */
  }

  return {
    schema_version: INDEX_SCHEMA_VERSION,
    catalog_mtime: catalogMtime,
    counts: {
      skills: skills.length,
      withTriggers: skills.filter((s) => s.triggers.length > 0).length,
      withCapability: skills.filter((s) => s.capability.length > 0).length,
      withRequires: skills.filter((s) => s.requires.mcps.length > 0).length,
    },
    skills,
    mcpProviders: buildMcpProviders(),
  };
}

/**
 * Map each MCP id to the profiles that DECLARE it.
 *
 * Deliberately reads the raw `mcps:` block of each profile.yaml rather than
 * resolving inheritance: an inherited answer would name every profile for
 * anything `core` declares, which tells the user nothing. "Which profile is
 * this MCP's home" is the useful question.
 */
function buildMcpProviders(root: string = join(repoRoot(), "profiles")): Record<string, string[]> {
  const providers: Record<string, string[]> = {};
  let entries: string[] = [];
  try {
    entries = readdirSync(root, { withFileTypes: true })
      .filter((d) => d.isDirectory() && !d.name.startsWith("_"))
      .map((d) => d.name);
  } catch {
    return providers;
  }

  for (const profile of entries) {
    let raw: string;
    try {
      raw = readFileSync(join(root, profile, "profile.yaml"), "utf8");
    } catch {
      continue;
    }
    let doc: { mcps?: unknown };
    try {
      doc = parseYaml(raw) as { mcps?: unknown };
    } catch {
      continue;
    }
    if (!Array.isArray(doc.mcps)) continue;
    for (const item of doc.mcps) {
      const id = typeof item === "string" ? item : (item as { id?: string } | null)?.id;
      if (typeof id !== "string" || !id) continue;
      const key = id.toLowerCase();
      (providers[key] ??= []).push(profile);
    }
  }

  for (const key of Object.keys(providers)) providers[key] = [...new Set(providers[key]!)].sort();
  return providers;
}

/** The bash generator wraps some descriptions in stray single quotes. */
function stripWrappingQuotes(s: string): string {
  const t = s.trim();
  if (t.length >= 2 && ((t.startsWith("'") && t.endsWith("'")) || (t.startsWith('"') && t.endsWith('"')))) {
    return t.slice(1, -1).trim();
  }
  return t;
}

function dedupeCI(values: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const v of values) {
    const t = v.trim();
    if (!t) continue;
    const k = t.toLowerCase();
    if (seen.has(k)) continue;
    seen.add(k);
    out.push(t);
  }
  return out;
}

/** Atomic write so a reader never sees a half-written index. */
export function writeIndex(index: SkillIndex, out: string = indexPath()): void {
  mkdirSync(dirname(out), { recursive: true });
  const tmp = `${out}.tmp`;
  writeFileSync(tmp, `${JSON.stringify(index, null, 2)}\n`);
  renameSync(tmp, out);
}

/** Read the index. Returns null on any failure — every caller falls back. */
export function loadIndex(path: string = indexPath()): SkillIndex | null {
  try {
    const parsed = JSON.parse(readFileSync(path, "utf8")) as SkillIndex;
    if (!Array.isArray(parsed.skills)) return null;
    return parsed;
  } catch {
    return null;
  }
}

/** True when the index is missing or older than the catalog it derives from. */
export function isIndexStale(index: string = indexPath(), catalog: string = catalogPath()): boolean {
  if (!existsSync(index)) return true;
  try {
    return statSync(catalog).mtimeMs > statSync(index).mtimeMs;
  } catch {
    return false; // can't stat the catalog — don't churn on a rebuild loop
  }
}

export interface ScoredHit {
  entry: IndexEntry;
  score: number;
  /** Which fields matched, for `--explain` and for the linter. */
  matched: string[];
}

export interface ScoreOptions {
  /** Skill ids already in the active profile — scored, then dropped. */
  exclude?: Iterable<string>;
  limit?: number;
  /** Minimum score to return. Defaults to {@link SUGGEST_THRESHOLD}. */
  threshold?: number;
}

/**
 * Score every skill against a free-text query.
 *
 * Two passes per skill: trigger phrases are matched as substrings against the
 * whole lowercased query (so multi-word triggers like "find EU tenders" work),
 * then individual tokens are matched against name/category/tags/capability/
 * description. `notFor` subtracts.
 */
export function scoreQuery(index: SkillIndex, query: string, opts: ScoreOptions = {}): ScoredHit[] {
  const haystack = ` ${query.toLowerCase()} `;
  const tokens = tokenize(query);
  if (tokens.length === 0 && haystack.trim().length === 0) return [];
  const tokenSet = new Set(tokens);
  const excluded = new Set(opts.exclude ?? []);
  const threshold = opts.threshold ?? SUGGEST_THRESHOLD;

  const hits: ScoredHit[] = [];
  for (const entry of index.skills) {
    if (excluded.has(entry.id)) continue;

    let score = 0;
    const matched: string[] = [];
    const hitTokens = new Set<string>();

    for (const phrase of entry.triggers) {
      const p = phrase.toLowerCase().trim();
      if (p.length < MIN_TERM_LENGTH) continue;
      if (haystack.includes(p)) {
        score += WEIGHTS.triggerPhrase;
        matched.push(`trigger:${p}`);
        for (const t of tokenize(p)) hitTokens.add(t);
      }
    }

    score += scoreField(entry.name.toLowerCase().split(/[^a-z0-9]+/), tokenSet, WEIGHTS.name, "name", matched, hitTokens);
    score += scoreField([entry.category.toLowerCase()], tokenSet, WEIGHTS.category, "category", matched, hitTokens);
    score += scoreField(entry.tags.map((t) => t.toLowerCase()), tokenSet, WEIGHTS.tag, "tag", matched, hitTokens);
    score += scoreField(tokenize(entry.capability), tokenSet, WEIGHTS.capability, "capability", matched, hitTokens);
    score += scoreField(tokenize(entry.description), tokenSet, WEIGHTS.description, "description", matched, hitTokens);
    score += scoreField(tokenize(entry.notFor), tokenSet, WEIGHTS.notFor, "notFor", matched, hitTokens);

    if (score <= 0) continue;
    if (hitTokens.size >= 2) score = Math.round(score * MULTI_TOKEN_BONUS);
    if (score < threshold) continue;

    hits.push({ entry, score, matched });
  }

  hits.sort((a, b) => b.score - a.score || a.entry.id.localeCompare(b.entry.id));
  return opts.limit ? hits.slice(0, opts.limit) : hits;
}

function scoreField(
  values: string[],
  tokens: Set<string>,
  weight: number,
  label: string,
  matched: string[],
  hitTokens: Set<string>,
): number {
  let total = 0;
  for (const v of values) {
    if (!v || !tokens.has(v)) continue;
    total += weight;
    matched.push(`${label}:${v}`);
    if (weight > 0) hitTokens.add(v);
  }
  return total;
}

/**
 * Emit the flat lookup files the Tier 1 bash hook consumes.
 *
 * Two files, both `<key>\t<weight>\t<id>` so the matcher is a single awk sum:
 *   phrases.idx — full trigger phrases, matched as substrings
 *   terms.idx   — single tokens, matched against the prompt's token set
 *
 * `notFor` terms land in terms.idx with their negative weight, so the hook
 * gets anti-scope handling for free without a third file.
 */
export function writeMatcherIndex(index: SkillIndex, dir: string = matcherDir()): { phrases: number; terms: number } {
  mkdirSync(dir, { recursive: true });

  const phraseLines: string[] = [];
  const termLines: string[] = [];

  for (const entry of index.skills) {
    for (const phrase of entry.triggers) {
      const p = phrase.toLowerCase().trim().replace(/\s+/g, " ");
      if (p.length < MIN_TERM_LENGTH || p.includes("\t")) continue;
      phraseLines.push(`${p}\t${WEIGHTS.triggerPhrase}\t${entry.id}`);
    }

    const emit = (values: string[], weight: number) => {
      for (const v of values) {
        if (!v || v.length < MIN_TERM_LENGTH || v.includes("\t")) continue;
        termLines.push(`${v}\t${weight}\t${entry.id}`);
      }
    };
    emit(entry.name.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean), WEIGHTS.name);
    emit([entry.category.toLowerCase()], WEIGHTS.category);
    emit(entry.tags.map((t) => t.toLowerCase()), WEIGHTS.tag);
    emit(tokenize(entry.capability), WEIGHTS.capability);
    emit(tokenize(entry.description), WEIGHTS.description);
    emit(tokenize(entry.notFor), WEIGHTS.notFor);
  }

  const phrases = [...new Set(phraseLines)].sort();
  const terms = [...new Set(termLines)].sort();
  writeAtomic(join(dir, "phrases.idx"), `${phrases.join("\n")}\n`);
  writeAtomic(join(dir, "terms.idx"), `${terms.join("\n")}\n`);
  // Tunables the hook must agree with, read as shell vars.
  writeAtomic(
    join(dir, "weights.env"),
    [
      `CUE_IDX_THRESHOLD=${SUGGEST_THRESHOLD}`,
      `CUE_IDX_MULTI_BONUS=${MULTI_TOKEN_BONUS}`,
      `CUE_IDX_MIN_TERM=${MIN_TERM_LENGTH}`,
      `CUE_IDX_SKILLS=${index.skills.length}`,
      "",
    ].join("\n"),
  );

  return { phrases: phrases.length, terms: terms.length };
}

function writeAtomic(path: string, content: string): void {
  const tmp = `${path}.tmp`;
  writeFileSync(tmp, content);
  renameSync(tmp, path);
}
