import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { parse as parseYaml } from "yaml";

import { scoreQuery, type IndexEntry, type SkillIndex } from "./catalog-index";
import { parseSkillFromContent } from "./skill-router";

const SKILLS = [
  ".agents/skills/ai-slop-detector/SKILL.md",
  ".agents/skills/hydra/SKILL.md",
  ".agents/skills/reddit-skills/SKILL.md",
  ".agents/skills/reddit-skills/skills/reddit-auth/SKILL.md",
  ".agents/skills/reddit-skills/skills/reddit-content-ops/SKILL.md",
  ".agents/skills/reddit-skills/skills/reddit-explore/SKILL.md",
  ".agents/skills/reddit-skills/skills/reddit-interact/SKILL.md",
  ".agents/skills/reddit-skills/skills/reddit-publish/SKILL.md",
] as const;

function entryFrom(path: string): IndexEntry {
  const source = resolve(path);
  const content = readFileSync(source, "utf8");
  const frontmatter = parseYaml(content.split("---", 3)[1] ?? "") as {
    name: string;
    description: string;
    tags?: string[];
  };
  const parsed = parseSkillFromContent(frontmatter.name, content);

  return {
    id: frontmatter.name,
    name: frontmatter.name,
    category: frontmatter.tags?.[0] ?? "project",
    description: frontmatter.description,
    source,
    tags: frontmatter.tags ?? [],
    triggers: parsed.triggers,
    capability: parsed.capability,
    notFor: parsed.notFor,
    links: [],
    requires: { mcps: [] },
    quality: parsed.quality,
  };
}

const entries = SKILLS.map(entryFrom);
const index: SkillIndex = {
  schema_version: "test",
  catalog_mtime: 0,
  counts: {
    skills: entries.length,
    withTriggers: entries.filter((entry) => entry.triggers.length > 0).length,
    withCapability: entries.filter((entry) => entry.capability.length > 0).length,
    withRequires: 0,
  },
  skills: entries,
  mcpProviders: {},
};

const cases: Array<[prompt: string, expected: string]> = [
  ["Humanize this draft and flag anything that sounds AI-written", "ai-slop-detector"],
  ["Run Hydra for a deep security and architecture review", "hydra"],
  ["Am I logged in to Reddit?", "reddit-auth"],
  ["Search Reddit for discussions about local-first software", "reddit-explore"],
  ["Publish this image as a new Reddit post", "reddit-publish"],
  ["Upvote that Reddit post and save it", "reddit-interact"],
  ["Analyze subreddit trends and build an engagement campaign", "reddit-content-ops"],
  ["Use Reddit to search, publish, comment, and save in one workflow", "reddit-skills"],
];

const redditCollisions: Array<[prompt: string, expected: string]> = [
  ["Post a comment on Reddit", "reddit-interact"],
  ["Create a new text post on Reddit", "reddit-publish"],
  ["Check my Reddit login before publishing", "reddit-auth"],
  ["Research Reddit posts without commenting or voting", "reddit-explore"],
  ["Plan a Reddit content strategy, then publish and engage", "reddit-content-ops"],
];

const paraphrases: Array<[prompt: string, expected: string]> = [
  ["Does this paragraph read like it was generated by AI?", "ai-slop-detector"],
  ["What architecture blind spots am I missing?", "hydra"],
  ["Log me out of Reddit", "reddit-auth"],
  ["Show me this Reddit user's profile", "reddit-explore"],
  ["Share this link post to r/programming", "reddit-publish"],
  ["Downvote this Reddit post", "reddit-interact"],
  ["Track subreddit trends and plan an engagement campaign", "reddit-content-ops"],
  ["I need several Reddit actions in one workflow", "reddit-skills"],
];

const unrelatedPrompts = [
  "Publish this blog post on our company website",
  "Review this one-line syntax error",
  "Check whether my database session is authenticated",
  "Search the local filesystem for a configuration file",
  "Deploy and test the release in one workflow",
];

const crossSkillWorkflows = [
  "Search Reddit, then comment on the best result",
  "Browse a subreddit and save a post in one workflow",
  "Check Reddit login and publish a link post as one workflow",
];

function hits(prompt: string) {
  return scoreQuery(index, prompt, { limit: 8 });
}

describe("project skill routing", () => {
  for (const [prompt, expected] of cases) {
    test(`${prompt} -> ${expected}`, () => {
      expect(hits(prompt)[0]?.entry.id).toBe(expected);
    });
  }

  for (const [prompt, expected] of redditCollisions) {
    test(`collision: ${prompt} -> ${expected}`, () => {
      const ranked = hits(prompt);
      expect(ranked[0]?.entry.id).toBe(expected);
      const umbrellaRank = ranked.findIndex((hit) => hit.entry.id === "reddit-skills");
      expect(ranked.findIndex((hit) => hit.entry.id === expected)).toBeLessThan(
        umbrellaRank < 0 ? Number.POSITIVE_INFINITY : umbrellaRank,
      );
    });
  }

  for (const [prompt, expected] of paraphrases) {
    test(`paraphrase: ${prompt} -> ${expected}`, () => {
      expect(hits(prompt)[0]?.entry.id).toBe(expected);
    });
  }

  for (const prompt of unrelatedPrompts) {
    test(`unrelated: ${prompt} -> no project skill`, () => {
      expect(hits(prompt)).toEqual([]);
    });
  }

  for (const prompt of crossSkillWorkflows) {
    test(`cross-skill workflow: ${prompt} -> reddit-skills`, () => {
      expect(hits(prompt)[0]?.entry.id).toBe("reddit-skills");
    });
  }

  test("all project skills expose production-grade routing metadata", () => {
    for (const entry of entries) {
      expect(entry.description.length).toBeLessThanOrEqual(200);
      expect(entry.triggers.length).toBeGreaterThanOrEqual(3);
      expect(entry.quality).toBe("good");
    }
  });

  test("Reddit child skills do not claim the same explicit trigger", () => {
    const owners = new Map<string, string>();
    for (const entry of entries.filter((entry) => entry.id.startsWith("reddit-") && entry.id !== "reddit-skills")) {
      for (const trigger of entry.triggers) {
        const normalized = trigger.toLowerCase();
        expect(owners.get(normalized)).toBeUndefined();
        owners.set(normalized, entry.id);
      }
    }
  });
});
