/**
 * `cue ruler` core — distribute the active profile's rules into every target
 * agent's NATIVE rule file (CLAUDE.md, AGENTS.md, .cursorrules, .clinerules, …).
 *
 * Adopts the good ideas from ruler (github.com/intellectronica/ruler):
 *   - one source of truth → concatenated fan-out with `<!-- Source: … -->`
 *     markers for traceability
 *   - whole-file write + `.bak` backup, and a clean `revert`
 *
 * cue-native deltas (deliberate improvements over ruler):
 *   - the single source is the resolved profile's `rules[]` (resources/rules/),
 *     not a separate `.ruler/` dir — zero new config
 *   - generated files carry a stable {@link RULER_MARKER}; `revert` only deletes
 *     a file it can prove cue generated, so a hand-written AGENTS.md is never
 *     blown away by a stray `--revert`
 *   - agents that share a native file (codex + amp → AGENTS.md) are written once
 *
 * Pure module: all side effects funnel through node:fs and every entry point
 * supports `dryRun`, so the logic is unit-testable against a tmpdir.
 */

import {
  readFileSync,
  writeFileSync,
  existsSync,
  copyFileSync,
  mkdirSync,
  rmSync,
} from "node:fs";
import { dirname, isAbsolute, join, relative } from "node:path";

import { repoRoot } from "./repo-root";
import type { AgentAdapter } from "./agent-adapters";

/** Lazy so CUE_REPO_ROOT set per-session (worktrees) is honored at call time. */
function rulesRoot(): string {
  return join(repoRoot(), "resources", "rules");
}

/**
 * Stable provenance marker stamped at the top of every generated file. Used to
 * (a) detect a prior `cue ruler` write and (b) gate `revert`'s delete so we
 * never remove a file cue did not author.
 */
export const RULER_MARKER = "<!-- cue:ruler -->";

const HEADER =
  `${RULER_MARKER}\n` +
  "<!-- Generated by `cue ruler` — edit the rules in resources/rules/ " +
  "(or your profile's rules[]), not this file. Re-run `cue ruler` to refresh, " +
  "`cue ruler --revert` to undo. -->";

export interface GatheredRule {
  /** Profile ref, normalized with .md (e.g. "common/security.md"). */
  source: string;
  /** Trimmed file contents. */
  content: string;
}

export type RulerActionKind =
  | "write" // wrote, no pre-existing file to back up
  | "backup+write" // backed up the existing file to .bak, then wrote
  | "skip-no-file" // adapter has no native rules file
  | "skip-shared" // another target already wrote this exact path this run
  | "dry-write"
  | "dry-backup+write"
  | "revert-restore" // restored the .bak
  | "revert-delete" // removed a cue-generated file (no .bak existed)
  | "revert-foreign" // a non-cue file sits here; left untouched
  | "revert-none" // nothing to revert
  | "dry-revert-restore"
  | "dry-revert-delete";

export interface RulerAction {
  agent: string;
  path: string | null;
  kind: RulerActionKind;
  backupPath?: string;
}

/** Resolve a profile rule ref (e.g. "common/security") to its file path. */
function ruleRefToPath(ref: string): { rel: string; abs: string } {
  const rel = ref.endsWith(".md") ? ref : `${ref}.md`;
  return { rel, abs: isAbsolute(rel) ? rel : join(rulesRoot(), rel) };
}

/** True iff `p` resolves inside `root` (blocks absolute / `..` ref escapes). */
function isWithin(root: string, p: string): boolean {
  const r = relative(root, p);
  return r === "" || (!r.startsWith("..") && !isAbsolute(r));
}

/**
 * Read each profile rule ref from resources/rules/, preserving declared order.
 * Missing or unreadable refs are skipped (the profile may out-live a rule file).
 */
export function gatherRules(rules: string[]): GatheredRule[] {
  const out: GatheredRule[] = [];
  const root = rulesRoot();
  for (const ref of rules) {
    const { rel, abs } = ruleRefToPath(ref);
    // Defense in depth: never read outside resources/rules/ even if a profile
    // ref is absolute or contains `..` (matters if profiles are ever loaded
    // from an external registry rather than the user's own tree).
    if (!isWithin(root, abs)) continue;
    if (!existsSync(abs)) continue;
    try {
      out.push({ source: rel, content: readFileSync(abs, "utf8").trim() });
    } catch {
      /* unreadable — skip */
    }
  }
  return out;
}

/** Concatenate gathered rules into one blob with ruler-style source markers. */
export function concatRules(rules: GatheredRule[]): string {
  const blocks = rules.map((r) => `<!-- Source: ${r.source} -->\n${r.content}`);
  return `${HEADER}\n\n${blocks.join("\n\n")}\n`;
}

export interface ApplyOpts {
  adapters: AgentAdapter[];
  content: string;
  targetDir: string;
  dryRun?: boolean;
}

/**
 * Write `content` into each adapter's native rules file. Whole-file model:
 * the first time a real file is overwritten, its prior contents are saved to
 * `<path>.bak` (never clobbering an existing .bak — that holds the true
 * pre-ruler state). Agents that resolve to the same path are written once.
 */
export function applyRuler(opts: ApplyOpts): RulerAction[] {
  const { adapters, content, targetDir, dryRun } = opts;
  const actions: RulerAction[] = [];
  const processed = new Set<string>();

  for (const adapter of adapters) {
    const path = adapter.rulesFile(targetDir);
    if (!path) {
      actions.push({ agent: adapter.id, path: null, kind: "skip-no-file" });
      continue;
    }
    if (processed.has(path)) {
      actions.push({ agent: adapter.id, path, kind: "skip-shared" });
      continue;
    }
    processed.add(path);

    const exists = existsSync(path);
    const bak = `${path}.bak`;
    // Back up only the FIRST overwrite — a pre-existing `.bak` is assumed to be
    // ours and holds the true pre-ruler state. (Caveat: a third-party `.bak`
    // left by another tool would be treated as that state on revert.)
    const willBackup = exists && !existsSync(bak);

    if (dryRun) {
      actions.push({
        agent: adapter.id,
        path,
        kind: willBackup ? "dry-backup+write" : "dry-write",
        backupPath: willBackup ? bak : undefined,
      });
      continue;
    }

    mkdirSync(dirname(path), { recursive: true });
    if (willBackup) copyFileSync(path, bak);
    writeFileSync(path, content);
    actions.push({
      agent: adapter.id,
      path,
      kind: willBackup ? "backup+write" : "write",
      backupPath: willBackup ? bak : undefined,
    });
  }
  return actions;
}

export interface RevertOpts {
  adapters: AgentAdapter[];
  targetDir: string;
  keepBackups?: boolean;
  dryRun?: boolean;
}

/**
 * Undo a prior `cue ruler` run. For each native rules file:
 *   - if a `.bak` exists → restore it (and drop the .bak unless keepBackups)
 *   - else if the file exists AND carries {@link RULER_MARKER} → delete it
 *   - else → leave it (a foreign / hand-written file is never removed)
 */
export function revertRuler(opts: RevertOpts): RulerAction[] {
  const { adapters, targetDir, keepBackups, dryRun } = opts;
  const actions: RulerAction[] = [];
  const processed = new Set<string>();

  for (const adapter of adapters) {
    const path = adapter.rulesFile(targetDir);
    if (!path) {
      actions.push({ agent: adapter.id, path: null, kind: "skip-no-file" });
      continue;
    }
    if (processed.has(path)) {
      actions.push({ agent: adapter.id, path, kind: "skip-shared" });
      continue;
    }
    processed.add(path);

    const bak = `${path}.bak`;
    if (existsSync(bak)) {
      if (dryRun) {
        actions.push({ agent: adapter.id, path, kind: "dry-revert-restore", backupPath: bak });
      } else {
        copyFileSync(bak, path);
        if (!keepBackups) rmSync(bak);
        actions.push({ agent: adapter.id, path, kind: "revert-restore", backupPath: bak });
      }
      continue;
    }

    if (existsSync(path)) {
      let ours = false;
      try {
        ours = readFileSync(path, "utf8").includes(RULER_MARKER);
      } catch {
        ours = false;
      }
      if (!ours) {
        actions.push({ agent: adapter.id, path, kind: "revert-foreign" });
      } else if (dryRun) {
        actions.push({ agent: adapter.id, path, kind: "dry-revert-delete" });
      } else {
        rmSync(path);
        actions.push({ agent: adapter.id, path, kind: "revert-delete" });
      }
      continue;
    }

    actions.push({ agent: adapter.id, path, kind: "revert-none" });
  }
  return actions;
}

/**
 * Append a managed `# cue ruler` block to .gitignore listing the generated
 * rule files and their .bak siblings, so they stay out of VCS. Idempotent:
 * skips paths already present. Returns the entries it added (empty if none).
 */
export function updateGitignore(
  targetDir: string,
  relPaths: string[],
  dryRun?: boolean,
): string[] {
  const gitignore = join(targetDir, ".gitignore");
  const existing = existsSync(gitignore) ? readFileSync(gitignore, "utf8") : "";
  const wanted = relPaths.flatMap((p) => [p, `${p}.bak`]);
  const added = wanted.filter((p) => !existing.split(/\r?\n/).includes(p));
  if (added.length === 0 || dryRun) return added;

  const block = `\n# cue ruler — generated agent rule files\n${added.join("\n")}\n`;
  writeFileSync(gitignore, existing + block);
  return added;
}

/**
 * Remove the managed `# cue ruler` block from .gitignore (the inverse of
 * {@link updateGitignore}), so `--revert` fully undoes a `--gitignore` apply.
 * No-op (returns false) when there is no .gitignore or no managed block.
 */
export function revertGitignore(targetDir: string, dryRun?: boolean): boolean {
  const gitignore = join(targetDir, ".gitignore");
  if (!existsSync(gitignore)) return false;
  const lines = readFileSync(gitignore, "utf8").split(/\r?\n/);
  const start = lines.findIndex((l) => l.startsWith("# cue ruler"));
  if (start === -1) return false;
  if (dryRun) return true;
  // Drop the marker + its contiguous entry lines, plus the single blank line
  // updateGitignore inserted before the block.
  let end = start + 1;
  while (end < lines.length && lines[end]!.trim() !== "") end++;
  const from = start > 0 && lines[start - 1] === "" ? start - 1 : start;
  writeFileSync(gitignore, [...lines.slice(0, from), ...lines.slice(end)].join("\n"));
  return true;
}
