import { describe, test, expect } from "bun:test";
import { generateSkillIndex } from "./skill-compressor";

describe("generateSkillIndex — threshold behaviour", () => {
  test("returns null when skillIds is empty (default threshold 10)", () => {
    expect(generateSkillIndex([])).toBeNull();
  });

  test("returns null when skillIds.length equals the threshold", () => {
    const ids = Array.from({ length: 10 }, (_, i) => `cat/skill-${i}`);
    expect(generateSkillIndex(ids, 10)).toBeNull();
  });

  test("returns null when skillIds.length is below the threshold", () => {
    const ids = Array.from({ length: 5 }, (_, i) => `cat/skill-${i}`);
    expect(generateSkillIndex(ids, 10)).toBeNull();
  });

  test("returns a string when skillIds.length exceeds the threshold", () => {
    const ids = Array.from({ length: 11 }, (_, i) => `nonexistent/fake-${i}`);
    const result = generateSkillIndex(ids, 10);
    expect(typeof result).toBe("string");
    expect(result).not.toBeNull();
  });

  test("custom threshold=1 with 2 ids returns a string", () => {
    const result = generateSkillIndex(["x/a", "x/b"], 1);
    expect(result).not.toBeNull();
  });

  test("custom threshold=2 with 2 ids returns null", () => {
    expect(generateSkillIndex(["x/a", "x/b"], 2)).toBeNull();
  });
});

describe("generateSkillIndex — output structure (with non-existent skill ids)", () => {
  const MANY = Array.from({ length: 12 }, (_, i) => `noop/fake-skill-${i}`);

  test("output starts with a skill index header", () => {
    const result = generateSkillIndex(MANY, 10)!;
    expect(result).toMatch(/^# Skill Index/);
  });

  test("output contains a markdown table header row", () => {
    const result = generateSkillIndex(MANY, 10)!;
    expect(result).toContain("| Skill | Trigger / Description | Category |");
  });

  test("output contains the auto-generated footer line", () => {
    const result = generateSkillIndex(MANY, 10)!;
    expect(result).toContain("Index auto-generated by cue");
  });

  test("reports correct skill count in header (0 when all ids missing on disk)", () => {
    const result = generateSkillIndex(MANY, 10)!;
    // Non-existent paths → summarizeSkill returns null → 0 resolved summaries
    expect(result).toContain("# Skill Index (0 skills loaded)");
  });
});
