/**
 * Tests for src/commands/export-docker.ts
 *
 * P3: hermetic help-text tests
 * P2: profile-based Dockerfile generation using a temp-dir fixture
 *
 * The internal pure functions (generateDockerfile, generateDockerignore,
 * extractCliDeps) are not exported; their behaviour is exercised via run().
 */

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { run } from "./export-docker";

// ---- stdout capture helpers ----

let stdoutLines: string[];
let stderrLines: string[];
let origStdoutWrite: typeof process.stdout.write;
let origStderrWrite: typeof process.stderr.write;

function captureOutput() {
  stdoutLines = [];
  stderrLines = [];
  origStdoutWrite = process.stdout.write.bind(process.stdout);
  origStderrWrite = process.stderr.write.bind(process.stderr);
  (process.stdout as any).write = (chunk: string | Uint8Array) => {
    stdoutLines.push(typeof chunk === "string" ? chunk : Buffer.from(chunk).toString());
    return true;
  };
  (process.stderr as any).write = (chunk: string | Uint8Array) => {
    stderrLines.push(typeof chunk === "string" ? chunk : Buffer.from(chunk).toString());
    return true;
  };
}

function restoreOutput() {
  process.stdout.write = origStdoutWrite;
  process.stderr.write = origStderrWrite;
}

// ---- temp dir / CWD helpers ----

let tmpDir: string;
let savedCwd: string;
let savedProfilesDir: string | undefined;

beforeEach(() => {
  tmpDir = mkdtempSync(join(tmpdir(), "cue-export-docker-"));
  savedCwd = process.cwd();
  savedProfilesDir = process.env.CUE_PROFILES_DIR;
  captureOutput();
});

afterEach(() => {
  restoreOutput();
  // Restore CWD first so rmSync doesn't fail on Windows (where you can't remove CWD)
  process.chdir(savedCwd);
  if (savedProfilesDir === undefined) {
    delete process.env.CUE_PROFILES_DIR;
  } else {
    process.env.CUE_PROFILES_DIR = savedProfilesDir;
  }
  rmSync(tmpDir, { recursive: true, force: true });
});

// ---- Help-text tests (P3 — fully hermetic) ----

describe("cue export --docker — help text", () => {
  test("-h returns 0 and prints Usage", async () => {
    const code = await run(["-h"]);
    expect(code).toBe(0);
    const out = stdoutLines.join("");
    expect(out).toContain("Usage");
    expect(out).toContain("--profile");
    expect(out).toContain("--output");
    expect(out).toContain("--base");
  });

  test("--help returns 0 and prints Usage", async () => {
    const code = await run(["--help"]);
    expect(code).toBe(0);
    const out = stdoutLines.join("");
    expect(out).toContain("cue export --docker");
  });
});

// ---- Profile-based Dockerfile generation (P2) ----

describe("cue export --docker — Dockerfile generation", () => {
  function createMinimalProfile(profilesRoot: string, name: string) {
    const dir = join(profilesRoot, name);
    mkdirSync(dir, { recursive: true });
    writeFileSync(
      join(dir, "profile.yaml"),
      `name: ${name}\ndescription: Docker export test profile\n`,
    );
  }

  test("generates Dockerfile with correct base image and profile name", async () => {
    createMinimalProfile(tmpDir, "dockertest");
    process.env.CUE_PROFILES_DIR = tmpDir;

    // chdir to tmpDir so the .dockerignore.cue side-output lands there
    process.chdir(tmpDir);

    const outputPath = join(tmpDir, "Dockerfile.cue");
    const code = await run([
      "--profile", "dockertest",
      "--output", outputPath,
      "--base", "alpine:3.18",
    ]);

    expect(code).toBe(0);
    expect(existsSync(outputPath)).toBe(true);

    const content = readFileSync(outputPath, "utf8");
    expect(content).toContain("FROM alpine:3.18");
    expect(content).toContain("dockertest");
    // Profile copy instruction
    expect(content).toContain("COPY profiles/dockertest/");
    // Entrypoint is always claude
    expect(content).toContain('ENTRYPOINT ["claude"]');
  });

  test("generated Dockerfile has expected structural sections", async () => {
    createMinimalProfile(tmpDir, "structtest");
    process.env.CUE_PROFILES_DIR = tmpDir;
    process.chdir(tmpDir);

    const outputPath = join(tmpDir, "Dockerfile.structtest.cue");
    const code = await run([
      "--profile", "structtest",
      "--output", outputPath,
    ]);

    expect(code).toBe(0);
    const content = readFileSync(outputPath, "utf8");

    // Generated-by comment
    expect(content).toContain("Generated by: cue export --docker");
    // Default base image when --base is omitted
    expect(content).toContain("FROM oven/bun:1-slim");
    // Runtime env var for claude config
    expect(content).toContain("ENV CLAUDE_CONFIG_DIR");
    // Profile pin
    expect(content).toContain('echo "structtest"');
  });

  test("--output defaults to Dockerfile.cue in cwd", async () => {
    createMinimalProfile(tmpDir, "defaultout");
    process.env.CUE_PROFILES_DIR = tmpDir;
    process.chdir(tmpDir);

    // No --output flag → should write Dockerfile.cue in CWD (tmpDir)
    const code = await run(["--profile", "defaultout"]);

    expect(code).toBe(0);
    expect(existsSync(join(tmpDir, "Dockerfile.cue"))).toBe(true);
  });

  test("generates .dockerignore.cue alongside the Dockerfile", async () => {
    createMinimalProfile(tmpDir, "ignorefile");
    process.env.CUE_PROFILES_DIR = tmpDir;
    process.chdir(tmpDir);

    await run(["--profile", "ignorefile", "--output", join(tmpDir, "Dockerfile.cue")]);

    const ignoreFile = join(tmpDir, ".dockerignore.cue");
    expect(existsSync(ignoreFile)).toBe(true);
    const content = readFileSync(ignoreFile, "utf8");
    // Must at least exclude node_modules
    expect(content).toContain("node_modules");
    expect(content).toContain(".git");
  });

  test("stdout confirms the generated files", async () => {
    createMinimalProfile(tmpDir, "outputmsg");
    process.env.CUE_PROFILES_DIR = tmpDir;
    process.chdir(tmpDir);

    await run(["--profile", "outputmsg", "--output", join(tmpDir, "Dockerfile.cue")]);

    const out = stdoutLines.join("");
    expect(out).toContain("Generated");
    expect(out).toContain("outputmsg");
  });
});
